### PR TITLE
feat: application slash commands

### PR DESCRIPTION
**Pull request by janleigh**
### – Finished Commands

   - [x] `help`
   - [x] `invite`
   - [x] `commands`
   - [x] `avatar`
   - [x] `prefix`
   - [x] `language`
   - [x] `anilist`
   - [x] `whatanime`

### CODE REVIEW

**Comment by janleigh** [comment]
this is still not ready

**Comment by janleigh** [comment]
status: slash commands are broken

**Comment by janleigh** [comment]
Go rebase this shit @LichKing112

**Comment by janleigh** [comment]
rebased myself

**Comment by LichKing112** [comment]
i'm a genius

**Review by kunaishen — COMMENTED** [review]
test review wawaawawawaw﻿

**Review by kunaishen — APPROVED** [review]

**Comment by janleigh** [comment]
wtf lmao

**Review by LichKing112 — APPROVED** [review]
Everything's good to go!

**Pull request merged**
